#if defined _ApolloRP_SC_included
	#endinput
#endif

#define _ApolloRP_SC_included

#define SC_MAX_WEAPONS 31

enum _:SC_WEAPONS
{
	SC_CROWBAR = 1,
	SC_9MMHANDGUN = 2,
	SC_357 = 3,
	SC_9MMAR = 4,
	SC_CROSSBOW = 6,
	SC_SHOTGUN = 7,
	SC_RPG = 8,
	SC_GAUSS = 9,
	SC_EGON = 10,
	SC_HORNETGUN = 11,
	SC_HANDGRENADE = 12,
	SC_TRIPMINE = 13,
	SC_SATCHEL = 14,
	SC_SNARK = 15,
	SC_UZIAKIMBO = 16,
	SC_UZI = 17,
	SC_MEDKIT = 18,
	SC_PIPEWRENCH = 20,
	SC_MINIGUN = 21,
	SC_GRAPPLE = 22,
	SC_SNIPERRIFLE = 23
}