insert  into arp_doors values ('t|apta', 'apta')
insert  into arp_doors values ('t|aptb', 'aptb')
insert  into arp_doors values ('t|aptc', 'aptc')
insert  into arp_doors values ('t|aptd', 'aptd')
insert  into arp_doors values ('t|BANK', 'bank')
insert  into arp_doors values ('t|bank_front', 'bank_front')
insert  into arp_doors values ('t|BANK_office', 'bank_office')
insert  into arp_doors values ('t|Bar', 'venuzClub')
insert  into arp_doors values ('t|cia_hideout', 'cia_hideout')
insert  into arp_doors values ('t|condo1', 'condo1')
insert  into arp_doors values ('t|condo2', 'condo2')
insert  into arp_doors values ('t|Diner', 'diner')
insert  into arp_doors values ('t|dumbster2', 'dumpster2')
insert  into arp_doors values ('t|edeka_backroom', 'edeka')
insert  into arp_doors values ('t|edeka_counter', 'edeka')
insert  into arp_doors values ('t|Garage3', 'garage3')
insert  into arp_doors values ('t|Garage4', 'garage4')
insert  into arp_doors values ('t|gunshopdoor2', 'gunshop')
insert  into arp_doors values ('t|hideout3', 'hideout3')
insert  into arp_doors values ('t|hideout4', 'hideout4')
insert  into arp_doors values ('t|hideout_over_bank', 'hideout_over_bank')
insert  into arp_doors values ('t|hideroom', 'apta')
insert  into arp_doors values ('t|Hospital', 'Hospital')
insert  into arp_doors values ('t|hotel', 'hotel')
insert  into arp_doors values ('t|hotelroom1', 'hotel')
insert  into arp_doors values ('t|hotelroom2', 'hotel')
insert  into arp_doors values ('t|hotelroom3', 'hotel')
insert  into arp_doors values ('t|Office1', 'Office1')
insert  into arp_doors values ('t|Office2', 'Office2')
insert  into arp_doors values ('t|Office3', 'Office3')
insert  into arp_doors values ('t|Office4', 'Office4')
insert  into arp_doors values ('t|OMG_hideout', 'OMG_hideout')
insert  into arp_doors values ('t|Police_Department', 'ICPD')
insert  into arp_doors values ('t|storagedoor1', 'storage1')
insert  into arp_doors values ('t|storagedoor2', 'storage2')
insert  into arp_doors values ('t|storagedoor3', 'storage3')
insert  into arp_doors values ('t|storagedoor4', 'storageMain')
insert  into arp_doors values ('t|towerhideout', 'towerhideout')
insert  into arp_doors values ('t|Xeviclub', 'xeviClub')

insert  into arp_jobs values ('MCPD Jail Guard', 15, 'ap')
insert  into arp_jobs values ('MCPD Explorer', 20, 'ap')
insert  into arp_jobs values ('MCPD Officer', 30, 'a')
insert  into arp_jobs values ('MCPD Senior Officer', 35, 'a')
insert  into arp_jobs values ('MCPD Trainer', 40, 'a')
insert  into arp_jobs values ('MCPD Lieutenant', 50, 'a')
insert  into arp_jobs values ('MCPD Sergeant', 45, 'a')
insert  into arp_jobs values ('MCPD Captain', 60, 'a')
insert  into arp_jobs values ('MCPD Deputy Chief', 70, 'a')
insert  into arp_jobs values ('MCPD Chief', 80, 'a')
insert  into arp_jobs values ('Edeka Employee', 20, 't')
insert  into arp_jobs values ('Edeka Guard', 20, 't')
insert  into arp_jobs values ('Bank Guard', 20, 't')
insert  into arp_jobs values ('Bank Clerk', 20, 't')
insert  into arp_jobs values ('Bank Manager', 25, 't')
insert  into arp_jobs values ('Lawyer', 20, 't')
insert  into arp_jobs values ('City Judge', 30, 'e')
insert  into arp_jobs values ('Hobo', 15, 't')
insert  into arp_jobs values ('Advertiser', 15, 't')
insert  into arp_jobs values ('Postman', 15, 't')
insert  into arp_jobs values ('Photographer', 15, 't')
insert  into arp_jobs values ('Pizzaboy', 15, 't')
insert  into arp_jobs values ('Taxi Driver', 10, 't')
insert  into arp_jobs values ('Economist', 15, 't')
insert  into arp_jobs values ('Professor', 15, 't')
insert  into arp_jobs values ('Weapons Dealer', 15, 't')
insert  into arp_jobs values ('Reporter', 15, 't')
insert  into arp_jobs values ('Porn Star', 20, 't')
insert  into arp_jobs values ('Salesman', 20, 't')
insert  into arp_jobs values ('Bodyguard', 30, 't')
insert  into arp_jobs values ('Hitman', 25, 't')
insert  into arp_jobs values ('S.W.A.T Rookie', 50, 'a')
insert  into arp_jobs values ('S.W.A.T Member', 55, 'a')
insert  into arp_jobs values ('S.W.A.T Leader', 70, 'a')
insert  into arp_jobs values ('S.W.A.T Experienced', 60, 'a')
insert  into arp_jobs values ('MCMD Medic', 45, 'c')
insert  into arp_jobs values ('MCMD Nurse', 25, 'bp')
insert  into arp_jobs values ('MCMD Paramedic', 35, 'b')
insert  into arp_jobs values ('MCMD Doctor', 55, 'b')
insert  into arp_jobs values ('MCMD Head Doctor', 65, 'b')
insert  into arp_jobs values ('MCMD Advanced Brain Surgeon', 80, 'b')
insert  into arp_jobs values ('Spy', 30, 't')
insert  into arp_jobs values ('Thief', 20, 't')
insert  into arp_jobs values ('Terrorist', 40, 't')
insert  into arp_jobs values ('Drug Dealer', 20, 't')
insert  into arp_jobs values ('Chaffeur', 30, 't')
insert  into arp_jobs values ('Exotic Dancer', 15, 't')

insert  into arp_property values ('apta', 'Apartment A', '', '', 80000, 1, '', 0)
insert  into arp_property values ('aptb', 'Apartment B', '', '', 80000, 1, '', 0)
insert  into arp_property values ('aptc', 'Apartment C', '', '', 80000, 1, '', 0)
insert  into arp_property values ('aptd', 'Apartment D', '', '', 80000, 1, '', 0)
insert  into arp_property values ('bank', 'Nations Bank', '', '', 90000, 1, '', 0)
insert  into arp_property values ('cia_hideout', 'Hideout', '', '', 90000, 1, '', 0)
insert  into arp_property values ('condo1', 'Condo #1', '', '', 75000, 1, '', 0)
insert  into arp_property values ('condo2', 'Condo #2', '', '', 75000, 1, '', 0)
insert  into arp_property values ('diner', 'Rag Top Diner', '', '', 90000, 1, '', 0)
insert  into arp_property values ('dumpster2', 'Dumpster #2', '', '', 20000, 1, '', 0)
insert  into arp_property values ('edeka', 'Edeka', '', '', 80000, 1, '', 0)
insert  into arp_property values ('garage3', 'Garage #1', '', '', 40000, 1, '', 0)
insert  into arp_property values ('garage4', 'Garage #2', '', '', 40000, 1, '', 0)
insert  into arp_property values ('gunshop', 'Guns', '', '', 50000, 1, '', 0)
insert  into arp_property values ('hideout3', 'Hideout #1', '', '', 80000, 1, '', 0)
insert  into arp_property values ('hideout4', 'Hideout #2', '', '', 80000, 1, '', 0)
insert  into arp_property values ('hideout_over_bank', 'Hideout #3', '', '', 40000, 1, '', 0)
insert  into arp_property values ('Hospital', 'Iburg City Medical Department', '', '', 0, 1, 'bc', 0)
insert  into arp_property values ('hotel', 'Hotel del Iburg', '', '', 0, 1, '', 0)
insert  into arp_property values ('ICPD', 'Iburg City Police Department', '', '', 0, 1, 'ao', 0)
insert  into arp_property values ('Office1', 'Office #1', '', '', 30000, 1, '', 0)
insert  into arp_property values ('Office2', 'Office #2', '', '', 30000, 1, '', 0)
insert  into arp_property values ('Office3', 'Office #3', '', '', 30000, 1, '', 0)
insert  into arp_property values ('Office4', 'Office #4', '', '', 30000, 1, '', 0)
insert  into arp_property values ('OMG_hideout', 'Hideout #4', '', '', 90000, 1, 'n', 0)
insert  into arp_property values ('storage1', 'Storage #1', '', '', 40000, 1, '', 0)
insert  into arp_property values ('storage2', 'Storage #2', '', '', 40000, 1, '', 0) 
insert  into arp_property values ('storage3', 'Storage #3', '', '', 40000, 1, '', 0) 
insert  into arp_property values ('storageMain', 'Iburg Storage', '', '', 40000, 1, '', 0) 
insert  into arp_property values ('towerhideout', 'Tower Hideout', '', '', 90000, 1, '', 0)
insert  into arp_property values ('venuzClub', 'Venuz Club', '', '', 90000, 1, '', 0)
insert  into arp_property values ('xeviClub', 'Xevi Club', '', '', 90000, 1, '', 0)
