CREATE TABLE IF NOT EXISTS arp_jobs (name VARCHAR(32),salary INT(11),access VARCHAR(27),UNIQUE KEY (name))

insert  into arp_jobs values ('LPD Jail Guard', 15, 'ap')
insert  into arp_jobs values ('LPD Explorer', 20, 'ap')
insert  into arp_jobs values ('LPD Officer', 30, 'a')
insert  into arp_jobs values ('LPD Senior Officer', 35, 'a')
insert  into arp_jobs values ('LPD Trainer', 40, 'a')
insert  into arp_jobs values ('LPD Lieutenant', 50, 'a')
insert  into arp_jobs values ('LPD Sergeant', 45, 'a')
insert  into arp_jobs values ('LPD Captain', 60, 'a')
insert  into arp_jobs values ('LPD Deputy Chief', 70, 'a')
insert  into arp_jobs values ('LPD Chief', 80, 'a')
insert  into arp_jobs values ('Edeka Employee', 20, 't')
insert  into arp_jobs values ('Edeka Guard', 20, 't')
insert  into arp_jobs values ('Bank Guard', 20, 't')
insert  into arp_jobs values ('Bank Clerk', 20, 't')
insert  into arp_jobs values ('Bank Manager', 25, 't')
insert  into arp_jobs values ('Lawyer', 20, 't')
insert  into arp_jobs values ('City Judge', 30, 'e')
insert  into arp_jobs values ('Hobo', 15, 't')
insert  into arp_jobs values ('Advertiser', 15, 't')
insert  into arp_jobs values ('Postman', 15, 't')
insert  into arp_jobs values ('Photographer', 15, 't')
insert  into arp_jobs values ('Pizzaboy', 15, 't')
insert  into arp_jobs values ('Taxi Driver', 10, 't')
insert  into arp_jobs values ('Economist', 15, 't')
insert  into arp_jobs values ('Professor', 15, 't')
insert  into arp_jobs values ('Weapons Dealer', 15, 't')
insert  into arp_jobs values ('Reporter', 15, 't')
insert  into arp_jobs values ('Porn Star', 20, 't')
insert  into arp_jobs values ('Salesman', 20, 't')
insert  into arp_jobs values ('Bodyguard', 30, 't')
insert  into arp_jobs values ('Hitman', 25, 't')
insert  into arp_jobs values ('S.W.A.T Rookie', 50, 'a')
insert  into arp_jobs values ('S.W.A.T Member', 55, 'a')
insert  into arp_jobs values ('S.W.A.T Leader', 70, 'a')
insert  into arp_jobs values ('S.W.A.T Experienced', 60, 'a')
insert  into arp_jobs values ('LMD Medic', 45, 'c')
insert  into arp_jobs values ('LMD Nurse', 25, 'bp')
insert  into arp_jobs values ('LMD Paramedic', 35, 'b')
insert  into arp_jobs values ('LMD Doctor', 55, 'b')
insert  into arp_jobs values ('LMD Head Doctor', 65, 'b')
insert  into arp_jobs values ('LMD Advanced Brain Surgeon', 80, 'b')
insert  into arp_jobs values ('Spy', 30, 't')
insert  into arp_jobs values ('Thief', 20, 't')
insert  into arp_jobs values ('Terrorist', 40, 't')
insert  into arp_jobs values ('Drug Dealer', 20, 't')
insert  into arp_jobs values ('Chaffeur', 30, 't')
insert  into arp_jobs values ('Exotic Dancer', 15, 't')
